### ISSUE TITLE
Support running on .NET Framework 4 and later

### ISSUE THREAD

**Issue by billybednar** [jmalarcon/netversion#1]
This tool targets .NET 2.0, which means by default it will only run if you have a 2.0 to 3.5 runtime installed. On all currently supported versions of Windows, [the 3.5 runtime is an optional component that is not installed by default](https://blogs.msdn.microsoft.com/astebner/2007/03/14/mailbag-what-version-of-the-net-framework-is-included-in-what-version-of-the-os/). Windows will prompt you to download 3.5 if you try to run this tool and only have 4+ is installed.

One option is to [create an app.config file to enable forward compatibility](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-configure-an-app-to-support-net-framework-4-or-4-5). To prefer 4+ but still run back to 2.0, you want something like this:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0"/>
        <supportedRuntime version="v2.0.50727"/>
    </startup>
</configuration>
```

Unfortunately, you no longer have a single file deployment, but I think that's the only option other than retargeting.

**Comment by jmalarcon** [comment]
Hi:

AFAIK all Windows versions from Vista onward [include at least .NET 3.0 preinstalled](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies). Since the app doesn't have any dependencies on 3.x, just in 2.0, it should work with any version except 1.0.

I'd love to install a really old Windows version with Visual Studio 2003 and compile it to .NET 1.0 so that it worked even in that extreme case, but I didn't have the time yet.

Thanks.

**Comment by billybednar** [comment]
> Since the app doesn't have any dependencies on 3.x, just in 2.0, it should work with any version except 1.0.

That's not true. Version 4 will not run programs targeting earlier framework versions unless there is a config file allowing it to do so.

If you run this on a fresh Windows 10 install, which includes only 4.8, it will fail to run and prompt you to download 3.5. If you add the config file it runs fine.

**Comment by jmalarcon** [comment]
OK, I wasn't aware of that. I'll add the app.config then. Thanks again.

**Comment by jmalarcon** [comment]
I've added it and referenced this issue. I've updated the v1.0.0. release (didn't add a new release since it only has the new config file, but the code hasn't changed).
