### ISSUE TITLE
VirusTotal has 3 vendors flagging this as malicious

### ISSUE THREAD

**Issue by TheFiZi** [jmalarcon/netversion#11]
FYI

https://www.virustotal.com/gui/file/647bf21ffaa77136799acf979056df96968e9959bb4e03c1622a20cfbc3802a1

Might be worth contact them and submitting for re-evaluation?

**Comment by jmalarcon** [comment]
Hi Eric. Thank you very much for making letting me know!

I don't know why this 3 antivirus are obviously flagging the file as mailicious incorrectly. 've just contacted VirusTotal and let's hope they can fix it. I love that service and it's a pity that is failing with this tool 😖

I'll keep you posted here.

**Comment by jmalarcon** [comment]
Update: I contacted Virustotal the same day you informed about this and they told me to contact the antivirus vendors directly, which I did. As of today only SecureAPlus has fixed the issue. I'm waiting for Cynet and MaxSecure to respond... Keep waiting.

**Comment by jmalarcon** [comment]
Although I've not known anything from the 2 vendors I wrote flagging this as malicious software, I've just checked it again at VirtusTotal and it's cleared at least since a month ago.

Thanks again for letting me know. I'm closing this issue now.
