### ISSUE TITLE
How to run the tool ? Updating of the Readme file

### ISSUE THREAD

**Issue by aliasimkazmi** [jmalarcon/netversion#13]
I  was looking for an .exe file so I can run it and get the version of .net.

An update to the README.md can help with this so I know what I am supposed to do to get the version of the .net running on my system.

Is it supposed to be that I have to download and run the project locally to get the correct version ?

**Comment by jcastillo-johngroup** [comment]
What you're looking for can be found under releases: https://github.com/jmalarcon/DotNetVersions/releases

**Comment by jmalarcon** [comment]
Ummm, this one went unnoticed for me, sorry. Thanks @jcastillo-johngroup for your response.

@aliasimkazmi As Jong has already said, as with any other software on GitHub, you should go to the "Releases" section on the right and download the software from there. This is common knowledge and nobody indicates that on the readme. 

It's a simple command line app: just write its name and press ENTER, as explained in the readme.md file on the cover of the repo.

Cheers.
