### ISSUE TITLE
.NET Framework compatibility

### ISSUE THREAD

**Issue by ferenczy** [jmalarcon/netversion#5]
According to your documentation, _DotNetVersions_ should require _.NET Framework 2.0_ to be executed. Even though I have the latest _.NET Framework 4.8_ installed (the Developer Pack edition), when I execute _DotNetVersions_, it triggers the missing runtime dialog:

![Missing runtime dialog](https://user-images.githubusercontent.com/1712992/100958084-f2deaa00-351b-11eb-96ee-cd0d873be3dc.png)

Is it expected? I thought that _.NET Framework_ should be backwards compatible. Do I really need to install _.NET Framework 3.5_?

**Comment by ferenczy** [comment]
According to the Microsoft's [Version compatibility in .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/version-compatibility) document, the _.NET Framework_ should be fully backwards compatible:

> The .NET Framework 4.5 and later versions are backward-compatible with apps that were built with earlier versions of the .NET Framework. In other words, apps and components built with previous versions will work without modification on the .NET Framework 4.5 and later versions.

But there's also the following note, which may be the reason why _DotNetVersions_ require older runtime, I guess:

> However, by default, apps run on the version of the common language runtime for which they were developed, so you may have to provide a configuration file to enable your app to run on the .NET Framework 4.5 or later versions.

So it should be easily fixable, if I understood it right. Just [add recent _.NET Framework_ runtimes as supported runtimes to the app config](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/version-compatibility#Apps), so people won't need to install outdated versions.

I'm not sure what's the reason for that, why any app is not automatically able to be executed on a newer runtime.

**Comment by ferenczy** [comment]
And this is quite funny. I have manually downloaded the [.NET Framework 3.5 SP1 runtime](https://dotnet.microsoft.com/download/dotnet-framework/net35-sp1), executed the installer and it triggered the same missing runtime dialog. 😁 I guess I'm missing something...


Anyway, I have tried to use the "_Download and install this feature_" button on the missing runtime dialog and it ended up with this:

![Failed installation of .NET Framework 3.5](https://user-images.githubusercontent.com/1712992/100959856-76e66100-351f-11eb-95cb-abe89372564e.png)

I don't know what's wrong. I'm using quite vanilla machine, there was no messing with .NET Frameworks, I have just _.NET Core 3.1_ and _Visual Studio_ installed and today, I have installed the _.NET Framework 4.8_ (Developer Pack).

So I'm effectively not able to run your app since I'm not able to install the _.NET Framework 3.5_. ☹

**Comment by jmalarcon** [comment]
Hi:

Have you tried to run it with the `DotNetVersions.exe.config` accompanying file that is in the .zip file?  That file is needed for it to work with both 2.0 and 4.0 versions of the framework. If you execute the .exe file without it and only have the latest version, if won't work and will show the dialog that you are telling in the issue.

Try this and it will work. Tell me, please...
